"""Generate ``docs/parameters.md`` from the registry (owner: WP-0).

``ybcal params doc`` writes it; ``make docs`` calls that; a test asserts the committed file equals
:func:`render_markdown` byte for byte, so the doc can never drift from the registry.
"""

from __future__ import annotations

from collections import Counter

from ybcal.params.invariants import INVARIANTS
from ybcal.params.registry import (
    GROUPS,
    PARAMS_CPP,
    PARAMS_H,
    PINNED_BRANCH,
    PINNED_COMMIT,
    REGISTRY,
    REGTEST_FLAG_DEFAULTS,
    ParamSpec,
)
from ybcal.types import ParamValue

GROUP_TITLES: dict[str, str] = {
    "G1": "G1 — Price medians",
    "G2": "G2 — Volatility",
    "G3": "G3 — Collateral and classes",
    "G4": "G4 — Grace and abandonment",
    "G5": "G5 — Activation and enforcement",
    "G6": "G6 — Miner judgement and fees",
    "G7": "G7 — Supply cap and halts",
    "G8": "G8 — Price attestation",
    "G9": "G9 — Amounts and wallet policy",
    "R": "R — Release (per-release, not tuned)",
    "-": "Not studied — identity, design choices and protocol constants",
}


def fmt_value(v: ParamValue) -> str:
    """Human formatting: thousands separators for ints, lower-case bools, raw strings."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _klass_cell(s: ParamSpec) -> str:
    if s.klass == "derived":
        base = "derived (locked)" if s.consensus else "derived"
        return f"{base} from {', '.join(f'`{p}`' for p in s.parents)}"
    return s.klass


def _search_cell(s: ParamSpec) -> str:
    if s.step <= 0:
        return "—"
    lo, hi = s.bounds
    return f"{fmt_value(lo)}–{fmt_value(hi)} / {fmt_value(s.step)}"


def render_markdown() -> str:
    """The full ``docs/parameters.md`` text."""
    lines: list[str] = []
    w = lines.append
    w("# Yellowback parameters")
    w("")
    w("<!-- GENERATED by `ybcal params doc` from src/ybcal/params/registry.py. Do not edit by hand. -->")
    w("")
    w(f"Every field of `yellowback::Params` (`{PARAMS_H}`) and the `params.h` constants the rules read, "
      f"at ycash6 commit `{PINNED_COMMIT}` (branch `{PINNED_BRANCH}`). Mainnet is `SetCommon()` + "
      f"`MainParams()` in `{PARAMS_CPP}`; regtest is `RegtestParams()` with the six regtest flags at "
      "their defaults: " + ", ".join(f"`{k}={fmt_value(v)}`" for k, v in REGTEST_FLAG_DEFAULTS.items())
      + ". `ybcal params check` re-extracts both columns from source and fails on any difference.")
    w("")
    w("## Classes")
    w("")
    w("| Class | Meaning | How a change ships |")
    w("|---|---|---|")
    w("| locked | consensus-shaped among enforcing miners (K10) | new parameter set keyed by start height "
      "(L8; W19 freeze-then-fix) |")
    w("| excluded | informational, wallet default (L6), wallet/agent policy or node-local | patch release |")
    w("| per-release | `startHeight`, `enforceUntilHeight` (M14, L8) | every release; derived from the tip |")
    w("| constant | protocol constant | verified, never tuned |")
    w("| derived | fixed by a formula from a parent; locked when a rule reads it | follows its parent |")
    w("| meta | identity (network name, address version) | not calibrated |")
    w("")
    counts = Counter(s.klass for s in REGISTRY.values())
    w("Counts: " + ", ".join(f"{k} {counts[k]}" for k in ("locked", "excluded", "per-release", "derived",
                                                         "constant", "meta")) + f"; total {len(REGISTRY)}.")
    w("")
    w("Hashed (in the state-hash `ParamsRecord`, `view.h`): "
      + ", ".join(f"`{s.name}`" for s in REGISTRY.values() if s.hashed) + ".")
    w("")
    for g in GROUPS:
        rows = [s for s in REGISTRY.values() if s.group == g]
        if not rows:
            continue
        w(f"## {GROUP_TITLES[g]}")
        w("")
        w("| Field | Mainnet | Regtest | Class | Unit | Hashed | Rules | Search (bounds / step) | Meaning |")
        w("|---|---|---|---|---|---|---|---|---|")
        for s in rows:
            flag = f" (`{s.regtest_flag}`)" if s.regtest_flag else ""
            w(f"| `{s.name}` | {fmt_value(s.mainnet)} | {fmt_value(s.regtest)}{flag} | {_klass_cell(s)} | "
              f"{s.unit} | {'yes' if s.hashed else ''} | {', '.join(s.rules)} | {_search_cell(s)} | "
              f"{s.doc} |")
        notes = [s for s in rows if s.note]
        if notes:
            w("")
            for s in notes:
                w(f"- `{s.name}`: {s.note}")
        w("")
    w("## Invariants (PLAN §1.4)")
    w("")
    w("Checked on every candidate before simulation (`ybcal.params.invariants`). *Mainnet-scale* checks "
      "are skipped for regtest-scale sets; *proposed* checks come from the plan, not a node rule.")
    w("")
    w("| Invariant | Rule | Check | Scope |")
    w("|---|---|---|---|")
    for inv in INVARIANTS.values():
        scope = inv.scope + (", proposed" if inv.proposed else "")
        w(f"| `{inv.name}` | {inv.rule} | {inv.doc} | {scope} |")
    w("")
    return "\n".join(lines)
